Remove trial attribute
There's something wrong with the new xproj projects and xunit:

BasicTests.cs(15,10,15,14): .NET Framework 4.6 error CS0012: The type
'Attribute' is defined in an assembly that is not referenced. You must
add a reference to assembly 'System.Runtime, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Oh well.